### ISSUE TITLE
falscher Umbruch auf Seite 15

### ISSUE THREAD

**Issue by gernotstarke** [deinprogramm/schreibe-dein-programm#10]
"Add Teachpack. In dem Dialog, der dann erscheint,wähle image.rkt"

Das "image.rkt" steht rechts zu weit raus. LaTeX kann scheinbar kein "verbatim" umbrechen...

**Comment by hklaeren** [comment]
danke, ist notiert!

--
Prof. Dr. Herbert Klaeren          | klaeren@uni-tuebingen.de
Universität Tübingen, Informatik   | Voice    +49 7071 61 07 83
Jasminweg 21, 72076 Tübingen, Germany
http://pu.inf.uni-tuebingen.de/users/klaeren

**Comment by gernotstarke** [comment]
habe übrigens bei Ihnen damals (lange her) in Aachen an der RWTH noch Informatik gelernt :-)

(weiss aber nicht mehr welche Veranstaltungen genau..)

vG Gernot Starke

> Am 06.06.2019 um 12:39 schrieb hklaeren <notifications@github.com <mailto:notifications@github.com>>:
> 
> danke, ist notiert!
> 
> --
> Prof. Dr. Herbert Klaeren | klaeren@uni-tuebingen.de <mailto:klaeren@uni-tuebingen.de>
> Universität Tübingen, Informatik | Voice +49 7071 61 07 83
> Jasminweg 21, 72076 Tübingen, Germany
> http://pu.inf.uni-tuebingen.de/users/klaeren <http://pu.inf.uni-tuebingen.de/users/klaeren>
>

**Comment by hklaeren** [comment]
Ist auch schon gefixed
