### ISSUE TITLE
Baumrotation

### ISSUE THREAD

**Issue by chessgarf** [deinprogramm/schreibe-dein-programm#104]
Die Vorüberlegungen zur Baumrotation auf S. 384 sind für mich so nicht nachvollziehbar.
Dass die Rotation bei |X| > |Y| das Ungleichgewicht vermindert, ist zwar (unter der Vorannahme |X| << |Y|+|Z|) richtig, scheint im nachfolgenden Code aber nicht mehr verwendet zu werden.
Ob die einfache Rotation das Ungleichgewicht größer macht, folgt aber doch nicht aus |Y| > |Z|, sondern aus |X| > |Z|.
Dass man im Ergebnis dann einfach ein "großes" Y aufteilt, versteh ich wieder, den Zusammenhang mit der Erklärung nicht.

**Comment by mikesperber** [comment]
@chessgarf Da ist ein Tippfehler im Text. Macht der FIx oben es besser?

**Comment by chessgarf** [comment]
Ich bin nicht überzeugt, aber vielleicht stehe ich einfach auf dem Schlauch. 
Wir haben vorher ein kleines |X| links und ein viel größeres |Y| + |Z| rechts. Jetzt wollen wir klären, ob wir das Y insgesamt nach links zum X stecken sollen oder kompliziertere Lösungen brauchen. 
Wenn  |Y| < |Z| (wie im Code) oder wenn |Y| < |X|, dann ist die einfache Rotation auf jeden Fall sinnvoll. Aber weder |Y| > |X| noch |Y| > |Z| sagen doch irgendetwas darüber aus, ob |Y| + |Z| kleiner oder größer als |Y| + |X| ist. 
Meiner Meinung nach passt die ganze, durch den Fix auch nicht wesentlich veränderte Erklärung (jetzt Z. 1998-2001) nicht zum folgenden Code. Kann das daran liegen, dass der es sich möglicherweise gegenüber Deiner ursprünglichen Planung "zu einfach" macht und öfter die doppelte Rotation wählt als nötig?
Ansonsten kommt vielleicht etwas in Betracht wie
`Wenn aber $Y$ größer ist $Z$, dann macht die einfache Rotation das
Ungleichgewicht nicht unbedingt kleiner: Der eh große Brocken $Y$ tut sich
dann auch noch mit $X$ zusammen, während der vielleicht sehr kleine Brocken $Z$ rechts
ganz allein zurückbleibt. ` 
Jedenfalls wäre das meine Spekulation, was gemeint gewesen sein könnte.

**Comment by mikesperber** [comment]
So, ich habe es nochmal durchgeschaut, bei hoffentlich besserer geistiger Verfassung und die Buchstaben nochmal geändert. Jetzt besser, @chessgarf ?

**Comment by chessgarf** [comment]
Ich fühl mich als fürchterliche Nervensäge und es tut mir wahnsinnig leid, aber ich bin immer noch nicht zufrieden. Machen wir doch, wie wir in Kapitel 1 gelernt haben, ein paar Testfälle (`ratio` war glaub ich 5 in unserer Implementation):
x=10, y=10, z=41:  y ist kleiner z, einfache Rotation, neu ungefähr 20:41, passt.
x=10, y=41, z=10: y ist größer z, doppelte Rotation, passt.
x=10, y=25, z=26: y ist kleiner z, einfache Rotation, neu 35:26, passt. 
x=10, y= 26, z=25: y ist größer z, aber:
a) die einfache Rotation macht das Ungleichgewicht nicht größer, sondern deutlich kleiner, neues Verhältnis 36:25
b) die doppelte Rotation könnte dagegen je nach Aufbau von Y etwa bei y1=6, y2=20 zu einem neuen Verhältnis von 16:45 führen. Zulässig, aber deutlich schlechter als die einfache Rotation.
Der Punkt b ist okay, das könnte man mit etwas komplizierterer Logik vielleicht noch verbessern, aber das ist ja nicht der Zweck des Buches. 
Aber Punkt a widerspricht halt einfach nach wie vor der Behauptung in Z. 1998f. Glaub ich jedenfalls.

**Comment by mikesperber** [comment]
@chessgarf Danke für die Erläuterung! (Das nervt überhaupt nicht - die Fehler sind ja meine. Danke für die Geduld!)

Stimmt - der Text tut so, als sei das Kriterium hart, aber es ist nur eine Heuristik, die sicher eine *ausreichende* (nicht immer die beste) Balance herstellt.

Habe den Text nochmal überarbeitet und eine Aufgabe dazu gestellt. Besser?

**Comment by chessgarf** [comment]
Glücklich, satt und zufrieden.

**Comment by mikesperber** [comment]
Super, danke für Deine Geduld!
