### ISSUE TITLE
Kapitel: 1.9 check-expect mit rationalen oder reelen Zahlen

### ISSUE THREAD

**Issue by cceelen** [deinprogramm/schreibe-dein-programm#12]
DrRacket 7.0 ist auf die erste Sprachstufe eingestellt. Die Verwendung von check-expect scheint in der Kombination nur mit natuerlichen, aber nicht rationalen oder reelen Zahlen zu funktionieren:
```
> (define billig (lambda (kwh) (+ 4.9 (* 0.19 kwh))))
> (define watt-fuer-wenig (lambda (kwh) (+ 8.2 (* 0.16 kwh))))
> (watt-fuer-wenig 500)
88.2
> (check-expect (billig 10) 6.8)
check-expect cannot compare inexact numbers. Try (check-within test 6.8 range).
> 
```
Entweder habe ich einen Fehler in den Einstellungen, oder im Text sollte dann check-within-range verwendet werden.

**Comment by mikesperber** [comment]
Mit DrRacket 7.0 dürften Sie noch die Sprachebenen zu "Die Macht der Abstraktion" haben. Sie bräuchten aber die Sprachebenen zu "Schreibe Dein Programm!", die sind ab DrRacket 7.3 dabei.

**Comment by mikesperber** [comment]
(Bei "Die Macht der Abstraktion" wurden Zahlen mit Dezimalpunkt noch als IEEE-Floats interpretiert, bei "Schreibe Dein Programm!" sind es exakte Brüche.)

**Comment by cceelen** [comment]
Danke. Ich konnte 7.4 durch dieses PPA (https://launchpad.net/~plt/+archive/ubuntu/racket) installieren. Damit funktioniert es dann wie im Buch beschrieben. 

Die Einstellungen zur Sprachebene sehen fuer mich nach dem Upgrade zu 7.4 immer noch identisch zu der in 7.0 aus. 
> Dein Programm > Schreibe Dein Programm! - Anfaenger
![RacketLanguageSelection](https://user-images.githubusercontent.com/13715549/65391486-12037880-dd6a-11e9-8961-e5e725e80f22.png)
Welche darunterliegende Version verwendet wird oder zu welcher Version des Buches sie gehoert ist nicht ersichtlich. 
Im Buch selbst sind die Abbildungen  mit Racket 7.2 gemacht worden und ich bin bisher noch ueber keinen Absatz gestolpert in der eine mindest Version empfohlen wird.
Ich denke das es gerade fuer Anfaenger gut waere solch einer Verwirrung vorzubeugen.

**Comment by mikesperber** [comment]
In 7.0 gab es noch keine Sprachen "Schreibe Dein Programm!". Den Hinweis mit der Version nehme ich gern auf - ich sehe mal, was ich tun kann.
