### ISSUE TITLE
Signaturverletzungen beseitigen, Kapitel 6.2

### ISSUE THREAD

**Issue by thuttner** [deinprogramm/schreibe-dein-programm#14]
Hallo miteinander,
ich bearbeite aktuell das [Kapitel 6](https://github.com/deinprogramm/schreibe-dein-programm/blob/master/i1list.tex) und mir ist aufgefallen das nicht alle beschriebenen Anpassungen nötig sind, um die Signaturverletzungen zu beseitigen. Folgende Anpassungen (ab Zeile [502](https://github.com/deinprogramm/schreibe-dein-programm/blob/b6e4c59a17520af03ee71f443ab243b1348f34d5/i1list.tex#L506)) waren bei mir nicht mehr nötig:

`(: cons (%element (list-of %element) -> (cons-list %element)))`
`(: first ((cons-list %element) -> %element))`
`(: rest ((cons-list %element) -> (list-of %element)))`

Warum sind diese Anpassungen nicht mehr nötig?
Werden diese Signaturen in der Sprachebene vordefiniert? Oder habe ich etwas übersehen?
Vielen Dank für das Verfassen dieses Buches!

Hier mein Programmcode ohne Signaturverletzungen:
```
; Eine Liste ist eins der folgenden:
; - eine leere Liste
; - eine Cons-Liste

; leere Liste
(define-record-functions empty-list
  make-empty-list
  empty?)
(define empty (make-empty-list))

; Eine cons-Liste besteht aus:
; - dem ersten Element
; - einer Liste mit den restlichen Elementen
(: cons-list (signature -> signature))
(define-record-functions (cons-list element)
  cons
  cons?
  (first element)
  (rest (list-of element)))

(define list-of
  (lambda (element)
    (signature (mixed empty-list
          (cons-list element)))))

; leere Liste
(define list0 empty)
(define list1 (cons 42 empty))
(define list3 (cons 1 (cons 2 (cons 3 empty))))
(define list2 (cons 2.7183 (cons 3.14159 empty)))
(define list4 (cons 2 (cons 3 (cons 5 (cons 7 empty)))))
(define list5 (cons 1 list4))

; Summe der Elemente einer Liste von Zahlen berechenen
(: list-sum ((list-of number) -> number))
(check-expect (list-sum list2) 5.85989)
(check-expect (list-sum list3) 6)
(check-expect (list-sum list4) 17)
(check-expect (list-sum list0) 0)
(check-expect (list-sum list1) 42)

(define list-sum
  (lambda (list)
    (cond
      ((empty? list) 0)
      ((cons? list) (+ (first list)
                       (list-sum (rest list)))))))

; Produkt der Elemente einer Liste von Zahlen berechenen
(: list-product ((list-of number) -> number))
(check-expect (list-product list1) 42)
(check-expect (list-product list3) 6)
(check-expect (list-product list4) 210)
(define list-product
  (lambda (list)
    (cond ((empty? list) 1)
          ((cons? list) (* (first list)
                           (list-product (rest list)))))))

(define string-list (cons "Mike" (cons "Sperber" empty)))```

**Comment by mikesperber** [comment]
Good Point!

Irgendwie hatte ich mir eingebildet, daß vorher Signaturdeklarationen für `cons`, `first` und `empty` dagestanden hätten, also etwa so:

```
(: cons (number list-of-numbers -> cons-list))
(: first (cons-list -> number))
(: rest (cons-list -> list-of-numbers))
```

Wenn die dagestanden hätten, wären sie auch verletzt waren, standen sie aber nicht.

Habe den Text gerade korrigiert. Besser so?

PS: Vielen Dank für die Rückmeldung!

**Comment by thuttner** [comment]
Ja passt. Nichts zu danken. 
Ich habe auch noch ein paar kleine Typos gefunden. Ich würde zum Ende jedes Kapitels ein pull request stellen. Passt das?

**Comment by mikesperber** [comment]
Das wäre fantastisch!
