### ISSUE TITLE
DrRacket link is broken

### ISSUE THREAD

**Issue by Kelvur** [deinprogramm/schreibe-dein-programm#16]
### Problem

In the website https://www.deinprogramm.de/ the link in the footer to https://racket-lang.org/ it's broken. The link points to `http//racket-lang.org/` where the `s` and the colon are missing.

![image](https://user-images.githubusercontent.com/16467804/79074545-54cc7400-7ced-11ea-815d-5797d758322d.png)

### Posible Solution

Replace the link to `https://racket-lang.org/` or just `racket-lang.org`

Sorry, I don't know german so I don't know if this is the correct place to report a error.

**Comment by mikesperber** [comment]
Fixed - thanks for the note!
