### ISSUE TITLE
Anleitung für das Erstellen eines PDFs

### ISSUE THREAD

**Issue by ua74e3dqka** [deinprogramm/schreibe-dein-programm#4]
Hallo, 

ich versuche gerade den Build-Prozess für das PDF nachzuvollziehen, um es schließlich per travis-ci zu automatisieren. Leider tappe ich dabei im dunkeln, was die genauen Paketvoraussetzungen (Abhängigkeiten) anbelangt. 

Ich habe auf einem Ubuntu (Bionic) eine TexLive 2018 Minimalinstallation aufgesetzt und folgende Pakete händisch mit tlmgr nachinstalliert.

_xkeyval textcase titlesec zapfding pifont symbol psfrag stmaryrd xypic_

Dennoch, erhalte ich folgende Fehlermeldung:

```
! pdfTeX error (font expansion): auto expansion is only possible with scalable
fonts.
<recently read> \AtBeginShipoutBox

l.242   von Ivan Valbusa.}

!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on i1.log.
```

**Comment by mikesperber** [comment]
Super, danke!

**Comment by ua74e3dqka** [comment]
#5
