### ISSUE TITLE
Link zu `elemente/tile.rkt` kaputt

### ISSUE THREAD

**Issue by das-g** [deinprogramm/schreibe-dein-programm#82]
Die Code-Links in den Abschnitten _0.9 Code_
https://github.com/deinprogramm/schreibe-dein-programm/blob/431737f15827a64ca1f075536bf6b2f19538f34e/i1pre.tex#L138
und _1.5 Abstraktion und Applikation_
https://github.com/deinprogramm/schreibe-dein-programm/blob/431737f15827a64ca1f075536bf6b2f19538f34e/i1prog.tex#L593
führen zu https://raw.githubusercontent.com/deinprogramm/schreibe-dein-programm/master/elemente/tile.rkt, wo aber nichts gefunden wird.

Eine Datei dieses Namens existiert (zumindest [im derzeitigen Stand des Hauptbranches](https://github.com/deinprogramm/schreibe-dein-programm/tree/431737f15827a64ca1f075536bf6b2f19538f34e)) nicht. [Die Datei `elemente/generate.rkt`](https://github.com/deinprogramm/schreibe-dein-programm/blob/431737f15827a64ca1f075536bf6b2f19538f34e/elemente/generate.rkt) hat evtl. einen ähnlichen Inhalt, wie der zu verlinkende, ist mit ihren `save-image`-Anwendungen aber vermutlich ausführlicher, als `tile.rkt` sein sollte.

**Comment by mikesperber** [comment]
Hatte ich vergessen einzuchecken; behoben in 3a0c626a50e7738230c8a37825bb5aee0f2f0fd2.

Danke für den Hinweis!
