### ISSUE TITLE
Aufgabe 7.6 - Beispielantwort "record:pair"

### ISSUE THREAD

**Issue by chessgarf** [deinprogramm/schreibe-dein-programm#86]
Aufgabe 7.6 verlangt eine Funktion evens, die "eine Liste der geraden Zahlen ..." zurückgibt. Die dargestellte Beispielantwort zeigt (evens 1 10) ,→ #<record:pair 2 #<record:pair 4 #<record:pair 6 #<record:pair 8 #<record:pair 10 #<empty-list>>>>>>, sollte aber in diesem Zusammenhang wohl einfach → #<list 2 4 6 8 10> lauten, entsprechend bei der zweiten Teilaufgabe.

**Comment by mikesperber** [comment]
Danke!
