### ISSUE TITLE
Sprachlich missglückter Satz S. 212

### ISSUE THREAD

**Issue by chessgarf** [deinprogramm/schreibe-dein-programm#87]
Auf S. "212", 2. Absatz, heißt es 
"Endliche Mengen, also Mengen mit endlich vielen Elementen schreiben wir als Aufreihung
ihrer Elemente, eingeschlossen in geschweirte Klammern geschlossen werden:"

Der letzte Halbsatz soll vermutlich "eingeschlossen in geschweiften Klammern:" lauten.

**Comment by mikesperber** [comment]
Danke!
