### ISSUE TITLE
Falscher Wert auf S. 228

### ISSUE THREAD

**Issue by chessgarf** [deinprogramm/schreibe-dein-programm#88]
Auf S. "228" Abs. 4 heißt es:
"Diese Funktion «heißt» J K5 – für einen
Ausdruck e liefert JeK den Wert 1, falls der Ausdruck «wahr» ist und 1, falls «falsch»."

Der zweite Wert muss wohl 0 lauten (und ein Komma zwischen "ist" und "und" wird auch nicht schaden).

**Comment by mikesperber** [comment]
Danke!
