### ISSUE TITLE
(make-dillo (dillo-alive? dillo) (dillo-weight dillo)) = dill

### ISSUE THREAD

**Issue by TheKarcher** [deinprogramm/schreibe-dein-programm#91]
Hier:
https://github.com/deinprogramm/schreibe-dein-programm/blob/2da4bab322417968cffbe21c8443a703a68cd803/i1zus.tex#L1263

wurden wohl die beiden Argument vertauscht. Korrekt ware zuerst dillo-weight und dann dillo-alive?

**Comment by mikesperber** [comment]
So isses - danke!
