### ISSUE TITLE
cons-list-of anstatt cons-list

### ISSUE THREAD

**Issue by TheKarcher** [deinprogramm/schreibe-dein-programm#93]
https://github.com/deinprogramm/schreibe-dein-programm/blob/2da4bab322417968cffbe21c8443a703a68cd803/i1list.tex#L469

Ich denke hier sollte es lauten:
Diese Record-Definition definiert cons-list**-as** als Funktion, die eine Signatur akzeptiert ...

Aber auch in den folgenden Zeilen könnte es sein, dass die Verwendung der Wörter "cons-list" und "cons-list-of" etwas durcheinander geraten ist. Oder es ist nur mein Verständnisproblem :)

**Comment by mikesperber** [comment]
In der Tat - vielen Dank! (Habe hoffentliche alle falschen Vorkommen gefixt.)
