### ISSUE TITLE
Signatur list-fold-left

### ISSUE THREAD

**Issue by chessgarf** [deinprogramm/schreibe-dein-programm#98]
Auf S. 305 wird die Signatur von list-fold-left mit 
`(: list-fold-left ((list-of %a) %acc (%acc %a -> %acc) (%acc -> %b) -> %b))` 
erarbeitet. Die next-acc-Funktion rufen wir aber mit `(next-acc (first list) acc)` auf,
also sollte die Signatur vermutlich
`(: list-fold-left ((list-of %a) %acc (%a %acc -> %acc) (%acc -> %b) -> %b))` lauten.

**Comment by mikesperber** [comment]
Danke!
