### ISSUE TITLE
Aufgabe 10.8 - Invariante?

### ISSUE THREAD

**Issue by chessgarf** [deinprogramm/schreibe-dein-programm#99]
Aufgabe 10.8 auf S. 306 lautet:
`Schreibe eine Version von power2 aus Abschnitt 7.4 auf Seite 206 mit Akkumulator. Hinweis: Du
kannst die gleiche Invariante wie bei power verwenden.`
Die Invariante bei power war:
`; power ist base^(exponent0 - exponent)`

power2 iterativ zu gestalten ist ja nicht allzu schwer. Die empfohlene Invariante kann ich mit diesem Algorithmus aber nicht zusammenbringen!?

**Comment by mikesperber** [comment]
@chessgarf Um das beurteilen zu können, müßte ich die Lösung sehen. (Meine hat die gleiche Invariante.)

**Comment by chessgarf** [comment]
Okay, dann stehe ich wohl einfach auf dem Schlauch. Für mich drängt sich als Invariante nach dem Algorithmus von power2 `; power ist base0^exponent0 / base^exponent` auf, aber wenn Du sagst, es geht auch anders, werd ich halt noch länger nachdenken. Danke.

**Comment by mikesperber** [comment]
@chessgarf `base` bleibt mir immer gleich, also `base=base0`.

Es gilt also: `base0^exponent0 / base^exponent` = `base^exponent0 / base^exponent` = `base^(exponent0-exponent)`

Das ist genau die Invariante von `power`.
